### ISSUE TITLE
Suggestion: How to lock / unlock a house, room and or an object (locker)

### ISSUE THREAD

**Issue by SGTGunner** [RPFramework/RPFramework#15]
Greetings, this is not an issue but more around an example, it that I would like to create a module with the functionality to lock / unlock a house or a room. Any example of how to do that using the RPFramework?

Thanks.

**Comment by kerkkoh** [comment]
Hi! You would, first of all, follow the basic structure for modules (README.md or Github wiki). After that you could, add interaction for locking a house and have that interaction run a script that will lock the house. I believe there is a thread on how to lock/unlock building doors: https://forums.bistudio.com/topic/152949-lockunlock-doors-on-a-builing/
look at tonic's response on that and you should get the idea.

You can lock objects with https://community.bistudio.com/wiki/lock but this doesn't work on houses.

**Comment by OfficialXtreme** [comment]
Housing confirmed ?

**Comment by SGTGunner** [comment]
@superihippo Thank you for the reply. I was not sure if I would get one. There has been not a lot of activity in the repo. Do you accept PRs from outside the RPF team?

**Comment by kerkkoh** [comment]
All PR's are welcome as long as they have been tested and are working 100%. When your PR gets accepted, you will be listed into the RPFramework team because of your contribution.

I have been busy with other projects lately so that's why there hasn't been much going on.

Housing confirmed if someone makes a module for it. I have stated this on my twitter: RPFramework is "finished" and now it's just up to people to build upon it and make their own modules to add functionality.
